name: weLearn
description: Democritized learning at your fingertips.
full_description: 'Make learning accessible everywhere. Cutting-edge features:<br>
<br>- <b>eBooks</b> &nbsp;&nbsp;&nbsp; Digitized books rental and library orders.
<br>- <b>Courses</b>&nbsp;&nbsp; Take online classes: lectures, challenges, auto-grading, etc.
<br>- <b>ClassX</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Share a whiteboard with peers in a classroom environment.
<br>- <b>Plaza</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An education marketplace: content, coaches, etc.'

android: https://ceduth.dev/
iOS: false
web: false
screenshots:
  - screenshot-discover.png
  - screenshot-books.png
  - screenshot-books-search.png
  - screenshot-books-book.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png


